
spring:
  application:
    name: product-service
  cloud:
   config:
    import-check:
      enable: false
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka